### PR TITLE
[MI-3768] Fixed the issue of headings not working properly from MS Teams to MM

### LINKED ISSUE #393: Bug:  Headings are not working properly from MS teams to MM.
## Steps to reproduce the bug

1. Go to the linked channel or DM/GM in MS teams.
2. Enter the text in the text area.
3. Select the desired text and select the heading type from the rich style dropdown.
4. Click on send button in MS teams and navigate to the linked channel or DM/GM in MM.

## Expected behaviour

The text should appear in the applied heading format in MM.

## Actual behaviour

The text is appearing within the HTML tags in MM.

## Screenshots (optional)

image
image

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
Fixed the issue of headings not working properly from MS Teams to MM

#### Ticket Link
Fixes #393

### CODE REVIEW

**Review by ayusht2810 — APPROVED** [review]

File: server/markdown/markdown.go [hunk 1]
```diff
@@ -11,6 +11,9 @@ var stringsToCheckForHTML = []string{
 	"<p ",
 	"<p>",
 	"<img ",
+	"<h1>",
+	"<h2>",
+	"<h3>",
```
Comment (lieut-data) [inline server/markdown/markdown.go:16]: Thanks, @manojmalik20! Are there unit tests we can update to add coverage here?

**Review by lieut-data — CHANGES_REQUESTED** [review]

**Review by lieut-data — APPROVED** [review]
Thanks @manojmalik20!

**Review by ayusht2810 — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested and approved. Working fine for all the heading types, LGTM.
